### ISSUE TITLE
server crash on 1.19.2

### ISSUE THREAD

**Issue by NantaArthur123** [Kzeroko/IsekaiWeaponry-Refabricated#1]
My server crashed when trying to right click a weapon from RWBY, I would really appreciate your help with this.

Modloader: Quilt

Game Version: 1.19.2

Crashlog:
[crash-2022-12-29_01.45.26-server.txt](https://github.com/Kzeroko/IsekaiWeaponry-Refabricated/files/10315589/crash-2022-12-29_01.45.26-server.txt)

**Comment by Kzeroko** [comment]
Should be fixed in the next version

**Comment by NantaArthur123** [comment]
Thank you for your hardwork
